// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXRjMYP4Dvuk5UKXPTUKPYDn4w4Xyg-KY',
    appId: '1:194115889709:web:73224feafe5b9136b4e6a4',
    messagingSenderId: '194115889709',
    projectId: 'microgreens-tracker-88d19',
    authDomain: 'microgreens-tracker-88d19.firebaseapp.com',
    storageBucket: 'microgreens-tracker-88d19.appspot.com',
    measurementId: 'G-S6SSPTFXLE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAitvROQt6Y7glgHBMnsJRDwmVRXvNVhKw',
    appId: '1:194115889709:android:ce7a96b7fc29135ab4e6a4',
    messagingSenderId: '194115889709',
    projectId: 'microgreens-tracker-88d19',
    storageBucket: 'microgreens-tracker-88d19.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDF4_-ZePeB7I6BB0eYDzi3LJvf4e8_Po',
    appId: '1:194115889709:ios:66f2330265445bb3b4e6a4',
    messagingSenderId: '194115889709',
    projectId: 'microgreens-tracker-88d19',
    storageBucket: 'microgreens-tracker-88d19.appspot.com',
    iosBundleId: 'com.example.microgreensTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDF4_-ZePeB7I6BB0eYDzi3LJvf4e8_Po',
    appId: '1:194115889709:ios:66f2330265445bb3b4e6a4',
    messagingSenderId: '194115889709',
    projectId: 'microgreens-tracker-88d19',
    storageBucket: 'microgreens-tracker-88d19.appspot.com',
    iosBundleId: 'com.example.microgreensTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXRjMYP4Dvuk5UKXPTUKPYDn4w4Xyg-KY',
    appId: '1:194115889709:web:288392f1b9ea8f5db4e6a4',
    messagingSenderId: '194115889709',
    projectId: 'microgreens-tracker-88d19',
    authDomain: 'microgreens-tracker-88d19.firebaseapp.com',
    storageBucket: 'microgreens-tracker-88d19.appspot.com',
    measurementId: 'G-77GGJ2SBS5',
  );
}
